### PR TITLE
Prevent gbanned users from using any command

### PR DESCRIPTION
**Pull request by SphericalKat**
Signed-off-by: ATechnoHazard <amolele@firehound.org>

### CODE REVIEW

**Comment by gotenksIN** [comment]
@ATechnoHazard Waw that's really cool

**Comment by skittles9823** [comment]
Wao

**Comment by SphericalKat** [comment]
@ATechnoHazard Actually you need to fix the indentation

**Comment by Yasir-siddiqui** [comment]
Wew nice tho

**Comment by yash-garg** [comment]
@ATechnoHazard Pro Af

**Comment by gotenksIN** [comment]
Has anyone merged this yet?

**Comment by SphericalKat** [comment]
Sed ;-;

**Comment by gotenksIN** [comment]
@ATechnoHazard Email replies are gay

**Pull request merged**
