### PR TITLE
Allow remote access to notes retrieval

### PR DESCRIPTION
**Pull request by gotenksIN**

### CODE REVIEW

**Comment by gotenksIN** [comment]
This doesn't work properly
Do not merge

**Comment by SphericalKat** [comment]
@songotenks69 Y u commit then sur

**Comment by gotenksIN** [comment]
@ATechnoHazard Coz me dumb ;-;

**Comment by skittles9823** [comment]
@songotenks69 10/10 dev sar

**Comment by yash-garg** [comment]
@songotenks69 is already beyond pro

**Pull request closed without merging**
