### PR TITLE
Add random animal picture commands

### PR DESCRIPTION
**Pull request by nyancrimew**
do not merge yet, I'll have to test this later

### CODE REVIEW

**Comment by skittles9823** [comment]
lol

**Comment by nyancrimew** [comment]
Ugh, the cat api is broken now

**Comment by yash-garg** [comment]
Nice module 😂🔥

**Comment by gotenksIN** [comment]
Sad that it doesn't work ;_;

**Comment by yash-garg** [comment]
@songotenks69 R.I.P

**Comment by skittles9823** [comment]
Press F for animals.

**Comment by gotenksIN** [comment]
@skittles9823 F

**Comment by msfjarvis** [comment]
API seems to work fine

**Comment by gotenksIN** [comment]
@MSF-Jarvis Last time I tried I got API errors so dunno

**Comment by nitanmarcel** [comment]
@songotenks69 I had a modified code of this with the same api and it worked.. If I remember right i changed the way I get the data from r (I think I used something else than json)

**Pull request closed without merging**
