### PR TITLE
ａｄｄ　ａｅｓｔｈｅｔｉｃ　ｖａｐｏｒｗａｖｅ　ｃｏｍｍａｎｄ

### PR DESCRIPTION
**Pull request by nyancrimew**

### CODE REVIEW

**Comment by nyancrimew** [comment]
oshit
I think I forgot to pass in args

**Comment by skittles9823** [comment]
@deletescape Omg yes.

**Comment by nyancrimew** [comment]
this will probably still not work, I forgot to adjust something for python3

**Comment by nyancrimew** [comment]
Should be good now

**Comment by yash-garg** [comment]
@deletescape Wow

**Pull request merged**
