### PR TITLE
Start migrating to saint for deepfrying

### PR DESCRIPTION
**Pull request by nyancrimew**
DO NOT MERGE (yet), this is essentially still WIP as saint does not yet support flares

### CODE REVIEW

**Comment by skittles9823** [comment]
@deletescape Yeeeessssss

**Comment by rupansh** [comment]
Use a proper face detection api rurt

**Comment by nyancrimew** [comment]
@rupansh I will, like it says there it is a start of a migration bhai

**Comment by rupansh** [comment]
@deletescape bhai then you can do everything with PIL if you have proper face detection api

**Pull request closed without merging**
