### PR TITLE
memes: Deepfry GIF's

### PR DESCRIPTION
**Pull request by rupansh**
haha yes
TODO: Compress the processed gif image
Removed API Token to prevent abuse(Yes you really need to switch from Microsoft's API to something else)
I am sure that the code can be better. So i made a PR to discuss it with the contributers

### CODE REVIEW

**Comment by gotenksIN** [comment]
@rupansh Peru af

**Comment by rupansh** [comment]
@songotenks69 nu sur

**Comment by timocapa** [comment]
sir pls no merge

**Comment by rupansh** [comment]
> sir pls no merge
excuse

**Comment by SphericalKat** [comment]
-1 -2 abandoned

**Comment by skittles9823** [comment]
Big oof

**Comment by rupansh** [comment]
> -1 -2 abandoned

Wat

**Comment by rupansh** [comment]
Ready to merge
Quick edit - I forgot to add file size and fps limit w8 before merging

**Comment by skittles9823** [comment]
Wewewew

**Comment by yash-garg** [comment]
@skittles9823 wew

**Comment by rupansh** [comment]
Quick update- Need to make it so that it processes everything in memory instead of making files. it was acceptable in stickers as they could be processed fast. When the bot is overloaded, it will be a real big problem

**Comment by yash-garg** [comment]
@rupansh Proo asf

**Comment by rupansh** [comment]
@Yash-Garg nu sur

**Comment by yash-garg** [comment]
@rupansh Yes sur

**Comment by SphericalKat** [comment]
WAAAAW PRUUUUU

**Comment by SphericalKat** [comment]
@ATechnoHazard Email replies are retarded ;_;

**Comment by yash-garg** [comment]
> 
> 
> @ATechnoHazard Email replies are retarded ;_;

You were the one who replied so.........

**Comment by gotenksIN** [comment]
@Yash-Garg But he didn't use email 🤔🤔

**Comment by 1maverick1** [comment]
@songotenks69 I guess he did.

**Pull request merged**
