### PR TITLE
Dildo

### PR DESCRIPTION
**Pull request by AnggaR96s**

### CODE REVIEW

**Comment by nyancrimew** [comment]
@AnggaR96s Yea maybe don't do that

**Comment by nitanmarcel** [comment]
@AnggaR96s Hey, my /420 command was there 😍

**Comment by raphielscape** [comment]
Wah si pangsad

**Comment by ghost** [comment]
Best commit in my life

**Comment by skittles9823** [comment]
Lmfao how about no

**Comment by nitanmarcel** [comment]
@skittles9823 Fuck yes.. Give me the D(ildo)

**Comment by krasCGQ** [comment]
Maaf, apakah manusia yang membuat ini PR pendukung pasangan **Ko**alisi Indo**n**esia **T**ronjal Tronj**ol** **M**aha **As**yik si Nomor 10 Nurha**di**-A**ldo**?

**Comment by RinKirito** [comment]
Oof,me need this

**Pull request closed without merging**
