### PR TITLE
memes: deepfry: handle stickers in memory

### PR DESCRIPTION
**Pull request by rupansh**
Untested but 99% chances of working

Always better for async bots

### CODE REVIEW

**Comment by baalajimaestro** [comment]
@rupansh Hmmm?

**Comment by nitanmarcel** [comment]
@rupansh Will work.. afaik

**Comment by rupansh** [comment]
@baalajimaestro we were handling stickers in storage when deepfrying. This hasn't caused a problem so far as deepfry is super fast with single images. However if the bot is overloaded with /deepfry on stickers, it might cause overwrites and unintentional stuff might happen

**Comment by baalajimaestro** [comment]
@rupansh Hash the name away

**Comment by rupansh** [comment]
> @rupansh Hash the name away

The file name will change on the fly in that case and again cause unintentional stuff

**Comment by rupansh** [comment]
processing in memory is faster anyways

**Comment by rupansh** [comment]
@skittles9823 merge bhai

**Comment by skittles9823** [comment]
@rupansh Sir you haven't tested yet

**Comment by nitanmarcel** [comment]
> Untested but 99% chances of working
> 
> Always better for async bots

Let it be 100%. Tested and working

**Comment by SphericalKat** [comment]
@nitanmarcel What a wao, problem is, skitt doesn't have too much memory

**Comment by rupansh** [comment]
Can't test nu serbor

**Comment by rupansh** [comment]
@ATechnoHazard A sticker is 512KB at most(Max limit kek) That isn't much memory

**Comment by yash-garg** [comment]
@rupansh Ohno ;_;

**Comment by nitanmarcel** [comment]
you can also get rid of  ```sticker.download('sticker.png')``` and use just ```image = Image.open(sticker)``` to avoid saving the file on the drive

**Comment by nitanmarcel** [comment]
Also the check if the file exists

**Comment by rupansh** [comment]
> Also the check if the file exists

Or just process it in the memory

**Comment by yash-garg** [comment]
@rupansh @gotenksIN every pro here, where are you?

**Comment by nitanmarcel** [comment]
yeah, but as @ATechnoHazard said the vps doesn't have so much memory

**Comment by rupansh** [comment]
@nitanmarcel 512 KB isn't much memory. Deepfried image is about the same so ~ 1-2 MB of memory usage more excluding the memory taken up by the python interpreter. We already process photos in the memory anyways

**Comment by nitanmarcel** [comment]
Oh, oki then ^^

**Pull request closed without merging**
