### PR TITLE
memes: Allow deepfrying stickers!

### PR DESCRIPTION
**Pull request by rupansh**
haha yes
Signed-off-by: rupansh <rupanshsekar@hotmail.com>

### CODE REVIEW

**Comment by 1maverick1** [comment]
@rupansh o.O

**Comment by SphericalKat** [comment]
Waw sur you pro as fuck

**Comment by timocapa** [comment]
Damn son where'd you kang that?!

**Comment by rupansh** [comment]
> Damn son where'd you kang that?!

I made it myself bish >.<

**Comment by SphericalKat** [comment]
@rupansh Lies

**Comment by rupansh** [comment]
@ATechnoHazard Not lying lel. I used the bits from getsticker function in sticker.py ;-;

**Comment by 1maverick1** [comment]
@rupansh Basically caught lying. Gg

**Comment by rupansh** [comment]
@1maverick1 Not really I have discussed this with Skittles already and personally asked him where is the getsticker function is lol. It just doesn't make sense to not use the bits from it.

**Comment by SphericalKat** [comment]
Pro re

**Comment by 4PERTURE** [comment]
Heccing nice

**Pull request merged**
