### PR TITLE
Add better spongemock and fix thonkification of reply text

### PR DESCRIPTION
**Pull request by rupansh**
dev pls merge

### CODE REVIEW

**Comment by yash-garg** [comment]
@rupansh Stickers don't appear in my samshit too

**Comment by rupansh** [comment]
@Yash-Garg Could it be because of Telegram X lmao? have you tried normal telegram on your samshit

**Comment by yash-garg** [comment]
@rupansh Nope i haven't tried normal one oO

**Comment by rupansh** [comment]
> @rupansh Nope i haven't tried normal one oO

@skittles9823 dev pls fix

**Comment by nitanmarcel** [comment]
@Yash-Garg The thonkify "fix" breaks the bot because is made like that to split the letters and then it checks the length

**Comment by nitanmarcel** [comment]
@nitanmarcel Or not.. I'm stoppid

**Comment by rupansh** [comment]
@nitanmarcel no it doesn't kek. I always test before pushing ;_;

**Comment by nitanmarcel** [comment]
@rupansh Yeah, I forgot I messed around with it and changed some codes :))

**Pull request merged**
