### PR TITLE
Create the kang pack when /kang is used for the first time

### PR DESCRIPTION
**Pull request by nyancrimew**
NOTE: As always this is not really tested yet, I do however see no reason why it would not be working!

### CODE REVIEW

**Comment by SphericalKat** [comment]
@deletescape OwO

**Comment by skittles9823** [comment]
@deletescape What a wow

**Comment by yash-garg** [comment]
@deletescape Pro tillu sir

**Comment by gotenksIN** [comment]
@deletescape As always ofcourse

**Comment by nyancrimew** [comment]
> @deletescape As always ofcourse

All code I write always works first try smh oc

**Comment by gotenksIN** [comment]
@deletescape Suuuuure

**Comment by skittles9823** [comment]
@deletescape Can't rebut this

**Pull request merged**
