### PR TITLE
Pluralize the locktype strings.

### PR DESCRIPTION
**Pull request by ayamdobhal**
Because it makes sense.
And it was tested successfully on https://github.com/songotenks69/ocbot.

### CODE REVIEW

**Comment by yash-garg** [comment]
@AyamDobhal Oof

**Comment by ayamdobhal** [comment]
> @AyamDobhal Oof

wat?

**Comment by yash-garg** [comment]
@AyamDobhal Change isn't required, go waste your time somewhere else

**Comment by ayamdobhal** [comment]
@Yash-Garg oof, I've talked to @skittles9823 about this before. Kthnxbye

**Comment by yash-garg** [comment]
**_New thug_** --> @AyamDobhal

**Comment by skittles9823** [comment]
@Yash-Garg It's a good change tho tbh.

**Comment by yash-garg** [comment]
@skittles9823 Runs away

**Comment by gotenksIN** [comment]
@Yash-Garg Nice typo 10/10

**Pull request merged**
